language: python

python:
#  - 2.6
  - 2.7
#  - 3.3
  - 3.4
  - 3.5
  - 3.6

install:
    # Temporary solution for Travis CI multiprocessing issue #943
    # https://github.com/travis-ci/travis-ci/issues/943
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    # Work around https://github.com/travis-ci/travis-ci/issues/5485
    - travis_retry pip install setuptools==29.0.1
    - pip install tox-travis coveralls

script: tox
after_success: coveralls --verbose
branches:
  only:
  - master
  - /^v.*$/
